name: 'Inputs'
description: 'A GitHub action that helps you better manage the input of your GitHub action. '
author: 'Payadel'

# Here we define the inputs, which can be set
# from the workflow file and are consumed in our code
inputs:
  inputs:
    description: "Inputs in yaml format"
    default: ''
    required: false
  log-inputs:
    description: log inputs or not?
    default: 'true'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
